skip_tags: true
clone_depth: 1

os: Visual Studio 2015

# Django 1.8 requires Python version >= 2.7
#
# Django 1.9 requires Python version >= 3.4
# if using Python 3
environment:
   matrix:
      - PYTHON_HOME: C:\Python27
        DJANGO_VERSION: 1.8
      - PYTHON_HOME: C:\Python27
        DJANGO_VERSION: 1.9
      - PYTHON_HOME: C:\Python33
        DJANGO_VERSION: 1.8
      - PYTHON_HOME: C:\Python34
        DJANGO_VERSION: 1.8
      - PYTHON_HOME: C:\Python34
        DJANGO_VERSION: 1.9
      - PYTHON_HOME: C:\Python35
        DJANGO_VERSION: 1.8
      - PYTHON_HOME: C:\Python35
        DJANGO_VERSION: 1.9

platform:
   - x86
   - x64

install:
   - IF [%PYTHON_HOME%]==[C:\Python32] appveyor DownloadFile https://www.python.org/ftp/python/3.2.5/python-3.2.5.msi
   - IF [%PYTHON_HOME%]==[C:\Python32] msiexec /i python-3.2.5.msi /qn
   - appveyor DownloadFile https://bootstrap.pypa.io/get-pip.py
   - '%PYTHON_HOME%\python get-pip.py'

build_script:
   - uname -a
   - df -h
   # Build into own virtualenv in order
   # to control the build environment
   - '%PYTHON_HOME%\Scripts\pip install virtualenv'
   - '%PYTHON_HOME%\Scripts\virtualenv venv'
   - venv\Scripts\activate
   - python -V
   - 'python -m pip install pip setuptools --ignore-installed'
   - 'pip install Django==%DJANGO_VERSION%'
   - pip install beautifulsoup4
   - pip install python-dateutil
   - pip install pytz

test_script:
   - cd gridSite && python manage.py test
